Add Video duration action
plainly-videos/nexrender pull request #20
Opened 2022-08-19 15:42 UTC by danixeee

An example action:

```json
"actions": {
  "prerender": [
    {
      "module": "@nexrender/action-video-duration",
      "input": "video.mp4",
      "output": "duration.txt"
    }
  ]
}
```

2022-08-21 11:41 UTC, ivansenic requested changes
@danixeee Left bunch of comments, can you please check..

2022-08-21 11:41 UTC, ivansenic commented on packages/nexrender-action-video-duration/package.json
> +  "version": "1.0.0",
are all the other versions `1.0.0` as well?

2022-08-21 11:41 UTC, ivansenic commented on packages/nexrender-action-video-duration/package.json
> +  "gitHead": "84cef65e008026f6fcf4f040943144401f101fce"
what's this?

2022-08-21 11:41 UTC, ivansenic commented on packages/nexrender-action-video-duration/ffmpeg.js
> +  new Date('1970-01-01T' + hmsTime + 'Z').getTime() / 1000;
What the fuck is this? Ok this is the biggest hack I saw in my life :smile:

2022-08-21 11:41 UTC, ivansenic commented on packages/nexrender-action-video-duration/ffmpeg.js
> +    return hmsToSeconds(hmsTimeRegexResult.pop()[1]);
* why using the index `[1]`?
* you are not checking that length is > 1 if you are targeting the index one?

2022-08-21 11:41 UTC, ivansenic commented on packages/nexrender-action-video-duration/ffmpeg.js
> +  const hmsTimeRegexResult = [...output.matchAll(FFMPEG_STDOUT_TIME_REGEX)];
why this array wrapping I don't get it?

2022-08-21 11:41 UTC, ivansenic commented on packages/nexrender-action-video-duration/index.js
> +      fs.writeFile(output, videoDuration.toPrecision(), (err) => {
what's `.toPrecision()`?

2022-08-21 11:41 UTC, ivansenic commented on packages/nexrender-action-video-duration/index.js
> +          resolve(job);
do we need to do this? so if we fail to write the file, why resolve a job? any other option?

2022-08-21 15:17 UTC, danixeee commented on packages/nexrender-action-video-duration/package.json
> +  "version": "1.0.0",
https://github.com/plainly-videos/nexrender/blob/master/packages/nexrender-action-fonts-plainly/package.json#L4 this one is, it depends but doesn't matter IMO

2022-08-21 15:17 UTC, danixeee commented on packages/nexrender-action-video-duration/package.json
> +  "gitHead": "84cef65e008026f6fcf4f040943144401f101fce"
No idea, I will remove it. I copied and modified another action.

2022-08-21 15:18 UTC, danixeee commented on packages/nexrender-action-video-duration/ffmpeg.js
> +  new Date('1970-01-01T' + hmsTime + 'Z').getTime() / 1000;
From the stack overflow ofc, but I liked it actually🤣

2022-08-21 15:26 UTC, danixeee commented on packages/nexrender-action-video-duration/ffmpeg.js
> +    return hmsToSeconds(hmsTimeRegexResult.pop()[1]);
the result of the regex is an array and index 1 is the capture group (value between `()` in the pattern)

<img width="521" alt="image" src="https://user-images.githubusercontent.com/16227576/185798478-f94253a9-ac66-497b-b7e2-d8d8d70f83d0.png">

if it's not matched at all, the array will be empty, so no need to check >1

2022-08-21 15:28 UTC, danixeee commented on packages/nexrender-action-video-duration/ffmpeg.js
> +  const hmsTimeRegexResult = [...output.matchAll(FFMPEG_STDOUT_TIME_REGEX)];
converting `RegExpStringIterator` to an array so I can call `pop()`

the output command of `ffmpeg` is writing the progress to the stderr and we have multiple matches (we only care about the last time=...)

2022-08-21 15:29 UTC, danixeee commented on packages/nexrender-action-video-duration/index.js
> +      fs.writeFile(output, videoDuration.toPrecision(), (err) => {
probably same as `toString()`

2022-08-21 15:31 UTC, danixeee commented on packages/nexrender-action-video-duration/index.js
> +          resolve(job);
@ivansenic I think we shouldn't raise any errors at this point because the video is already rendered and uploaded. So, if the file does not exist, or the value is 0.0, can you use the default duration?

2022-08-23 07:14 UTC, ivansenic commented on packages/nexrender-action-video-duration/ffmpeg.js
> +    return hmsToSeconds(hmsTimeRegexResult.pop()[1]);
OK, but it would be safer anyway..

2022-08-23 07:15 UTC, ivansenic commented on packages/nexrender-action-video-duration/index.js
> +          resolve(job);
That's correct, but why calling `resolve(job)`, what's this doing?

2022-08-23 07:15 UTC, ivansenic approved these changes
Have a look on the remaining comments..

2022-08-25 18:45 UTC, merged